root: true

env:
  es6: true
  jest: true
  browser: true

extends:
  - react-app
  - "@equal/eslint-config/typescript"
  - prettier
  - prettier/@typescript-eslint
  - prettier/standard

parserOptions:
  project: ./tsconfig.eslint.json

rules:
  "@typescript-eslint/no-floating-promises": off
  "@typescript-eslint/no-namespace": off
