root: true
env:
  es6: true
  jest: true
  browser: true
extends:
  - react-app
  - '@equal/eslint-config/typescript'
  - prettier
  - prettier/@typescript-eslint
  - prettier/standard
plugins:
  - '@typescript-eslint'
  - prettier
